/* ============================================================
 * SPURANA · practice/library.js — ALL practices, one module.
 * Data-driven so it upgrades per need: add a line to LIB and a
 * new guided practice appears. Categories: meditation, heart,
 * couple, awakening. A shared guided player runs timed phases
 * and logs to hc_logs (solo) or cp_logs (couple). Breath &
 * Metta route to their dedicated interactive engines.
 * ============================================================ */
(function () {
  "use strict";

  // each guided practice: { id, t:title, i:icon, d:desc, kind, log, phases:[[text,seconds]...] }
  const LIB = {
    meditation: [
      { id: "silence", t: "Sit in Silence", i: "\uD83E\uDDD8", d: "Open stillness \u2014 bells at start, middle, end.", kind: "silence", sound: "bowls", defMin: 10, log: "hc_logs" },
      { id: "breath", t: "Breathing", i: "\uD83C\uDF2C", d: "Guided breath patterns.", kind: "breath" },
      { id: "metta", t: "Loving-Kindness", i: "\uD83D\uDC97", d: "Send warmth outward.", kind: "metta" },
      { id: "stillness", t: "Stillness", i: "\uD83E\uDDD8", d: "Rest as awareness itself.", kind: "guided", sound: "om", log: "hc_logs", defMin: 8,
        phases: [["Let the body find its seat. Nothing to fix, nowhere to be.", 18, "Welcome. Let yourself arrive — the body settling like silt drifting slowly to the floor of still water.", "Feel the places that touch the ground."], ["Soften the face — the brow, the jaw, the throat.", 22, "Soften the face now. The space between the eyebrows, the hinge of the jaw, the small muscles around the eyes. Let them be heavy.", "Unclench. Let your face be kind."], ["Find the breath where it already is. Do not change it.", 30, "Find the breath exactly as it is. You needn't deepen or slow it. Only feel it, arriving and leaving on its own.", "Where do you feel the breath most clearly?"], ["Thoughts will come. Let them pass like weather across a wide sky.", 36, "A thought arrives — that is alright. You don't have to chase it or push it away. Watch it drift, and let it go.", "Notice one thought. Now let it dissolve."], ["Each time you wander, return — gently, without blame.", 40, "The moment you notice you've drifted, that noticing is the whole practice. Come home softly, again and again.", "Returning is the practice, not failing."], ["Now rest as the space in which all of this appears.", 44, "Let go of holding anything at all. Rest as the open space in which every sound, sensation and thought simply comes and goes.", "You are the sky, not the weather."], ["Stay. Be the stillness that was here before you arrived.", 40, "Simply be here. This stillness beneath everything was here long before you sat. Let it hold you now.", ""], ["Slowly let the breath deepen. Begin to return.", 12, "Gently now, let the breath grow a little fuller. Begin to come back, carrying the quiet with you.", "Bring this calm into what comes next."]] },
      { id: "bodyscan", t: "Body Scan", i: "\u2728", d: "Awareness through the body.", kind: "guided", sound: "bowls", log: "hc_logs", defMin: 8,
        phases: [["Lie or sit. Let the whole body grow heavy and supported.", 18, "Let the body be completely held by what's beneath it. You don't have to carry yourself for these minutes.", "Let the ground take your full weight."], ["Bring soft attention to the crown of your head.", 22, "Rest your attention gently on the very top of your head. Feel whatever is there — warmth, tingling, or nothing at all.", "Just notice. Nothing to change."], ["Let it flow down — the face, the throat, the shoulders.", 34, "Let attention move down like warm water — over the face, softening it; down the throat; spreading across the shoulders.", "Feel the shoulders drop away from the ears."], ["Down through the arms, to the palms and fingertips.", 34, "Down through the arms now, all the way to the hands. Feel the palms, and the faint pulse in the fingertips.", "Can you feel your own heartbeat there?"], ["Into the chest and belly, rising and falling with breath.", 36, "Rest in the chest and the belly, moving with each breath. Let this whole centre soften and open.", "Feel the breath rock the body, gently."], ["Down through the hips, the legs, to the soles of the feet.", 36, "Let it pour down through the hips and the legs, all the way to the soles of the feet, where you meet the earth.", "Feel the feet, heavy and alive."], ["Now feel the whole body at once — alive, and held.", 40, "Now hold the entire body in one soft awareness — every part glowing faintly, alive, and completely held.", "One body. One breath. Whole."], ["Rest here a moment, then gently return.", 12, "Stay in this wholeness a little longer. Then, when you're ready, let the breath deepen and return.", "Carry this body-warmth with you."]] },
      { id: "soham", t: "So-Ham", i: "\uD83D\uDD49", d: "The breath that says 'I am'.", kind: "guided", sound: "om", log: "hc_logs", defMin: 8, breath: [5, 1, 6, 1],
        phases: [["Settle. Let the breath find a slow, natural rhythm.", 20, "Let the breath slow on its own, like a tide finding its pace. There is nothing to force.", "Let the breath lengthen by itself."], ["On the inhale, silently hear the sound 'So'.", 40, "As the breath flows in, let it carry one silent sound — Soooo. Don't say it; simply hear it arrive with the air.", "Inhale … Sooo."], ["On the exhale, silently hear 'Ham'.", 40, "As the breath leaves, hear its answer — Hummm. The two sounds are the breath's own quiet song.", "Exhale … Hummm."], ["So … Ham … let the breath breathe you.", 70, "So … Ham … So … Ham. You are not making this happen. Let the breath, and its sound, breathe you.", "'So-Ham' — 'I am That.'"], ["Let the sounds soften until only their meaning remains.", 44, "Let the words grow fainter and fainter, until only the quiet sense of being remains, with no sound at all.", "Stay with the feeling beneath the words."], ["Dissolve the words. Just being.", 30, "Let even the meaning go. What's left is simply you, here, breathing, being. Rest in that.", ""], ["Gently return, carrying the quiet.", 12, "Slowly return. Let the breath deepen, and carry this simple sense of being into your day.", "I am. That is enough."]] },
      { id: "nidra", t: "Yoga Nidra", i: "\uD83C\uDF19", d: "Conscious deep rest.", kind: "guided", sound: "tanpura", log: "hc_logs", defMin: 15, breath: [4, 2, 8, 2],
        phases: [["Lie down. Let the body become completely still.", 24, "Lie back and let the body grow still — stiller than sleep, while you stay softly awake. You are safe to let go.", "Make one last adjustment, then be still."], ["Set a gentle intention — a single, quiet wish.", 26, "In a few soft words, plant one intention in the heart — a wish for yourself. Say it once, then release it.", "Whisper your wish, once, inwardly."], ["Let the body grow heavy, part by part.", 60, "Feel the right hand grow heavy … the left … both arms … the legs … the whole body sinking, warm and weightless.", "Let each part grow too heavy to lift."], ["You are about to rest while staying awake.", 40, "This is the threshold of sleep — but you will stay here, awake and aware, floating on the very edge.", "Keep one thread of awareness lit."], ["Sink deeper, but keep a single thread of awareness.", 80, "Sink further into the warmth and the dark. Let everything go — except the faint knowing that you are still here.", "The body sleeps; you remain."], ["The body sleeps; awareness remains, clear and quiet.", 60, "The body has gone to sleep, and yet awareness has not. Rest as that quiet light that never closes its eyes.", "Notice: you are aware of resting."], ["Gently call yourself back. Begin to stir.", 18, "Slowly, begin to return. Deepen the breath. Feel the fingers, the toes. Carry this deep rest back with you.", "Wiggle the fingers. Welcome back."]] },
      { id: "vipassana", t: "Vipassana", i: "\uD83D\uDC41", d: "Insight \u2014 seeing things as they are.", kind: "guided", sound: "bowls", log: "hc_logs", defMin: 12,
        phases: [["Sit upright. Let the eyes close. Simply arrive.", 24, "Sit with a straight, easy spine. Let the eyes close, and simply arrive in this moment, just as it is.", "Feel the body sitting, right now."], ["Rest attention at the nostrils — the bare touch of air.", 50, "Bring attention to the rim of the nostrils, and feel the bare sensation of air — cool coming in, warm going out.", "Feel only the touch of the breath."], ["Now scan the body slowly, part by part.", 70, "Begin to sweep attention slowly through the body, from the crown to the toes, meeting each part with bare attention.", "Move slowly. Miss nothing."], ["Whatever arises — an itch, an ache, a calm — just observe.", 70, "When something calls — an itch, a tension, a pleasant warmth — don't move to fix it. Simply observe it, exactly as it is.", "Observe without reacting."], ["Watch each sensation rise — and watch it pass.", 60, "Notice how nothing stays. Each sensation swells, peaks, and fades. You are watching impermanence itself, moment by moment.", "Rise … and pass. Nothing holds."], ["See how all of it is changing. Nothing is solid.", 50, "See it clearly: the body, the breath, the mind — all of it flowing, never fixed. This seeing is insight.", "Everything moves. Even 'you'."], ["Rest in bare awareness. Only knowing remains.", 40, "Let go of the scanning now. Rest as the simple knowing that was watching all along — silent, clear, at ease.", "Just knowing. Just this."]] },
      { id: "chakra", t: "Chakra Awakening", i: "\uD83C\uDF08", d: "The seven centres, base to crown.", kind: "guided", sound: "om", log: "hc_logs", defMin: 14,
        phases: [["Sit tall, the spine like a rising stem of light.", 24, "Let the spine rise tall and soft, like a stem growing toward light. We will climb it, centre by centre.", "Imagine a thread lifting the crown."], ["Root — Muladhara, deep red, at the base. Feel your ground.", 60, "Breathe into the base of the spine — Muladhara, glowing deep red. This is your root, your safety, your ground.", "I am safe. I am here."], ["Sacral — Svadhisthana, orange, below the navel.", 54, "Rise to the centre below the navel — Svadhisthana, warm orange. Let feeling and creativity flow freely here.", "Let feeling move, like water."], ["Solar plexus — Manipura, gold. Your inner fire.", 54, "Up to the solar plexus — Manipura, bright gold. Your will, your warmth, your quiet strength. Feel it glow.", "Feel your own steady power."], ["Heart — Anahata, green. Let it soften and open.", 60, "Rest at the heart — Anahata, soft green. Let it open like a flower, without fear. This is where you love.", "Breathe the heart open."], ["Throat indigo brow — your truth, and your seeing.", 60, "Rise to the throat, glowing blue — your truth; and the brow, deep indigo — your inner sight. Let both grow clear.", "Speak true. See clearly."], ["Crown — Sahasrara, violet light. The whole column alight.", 54, "Reach the crown — Sahasrara, violet and white, opening to the sky. The whole column of you is alight now.", "Feel the whole spine glowing."], ["Rest in the glow of all seven, humming as one.", 30, "Let all seven centres hum together, a single ladder of light. Rest in the whole of it, complete.", "One light, root to crown."]] },
      { id: "kundalini", t: "Kundalini Awareness", i: "\uD83D\uDC0D", d: "The serpent energy rising.", kind: "guided", sound: "tanpura", log: "hc_logs", defMin: 12,
        phases: [["Sit with a straight spine. Breathe slow and full.", 30, "Sit tall and breathe slowly, fully. We are going to invite a sleeping warmth to wake — gently, never by force.", "Long, full breaths. No strain."], ["Imagine a coiled light resting at the base of the spine.", 50, "Picture a coil of soft light asleep at the very base of the spine, patient and waiting. Just see it there.", "Rest your attention at the base."], ["With each inhale, invite it to stir.", 70, "With each slow inhale, gently invite that light to stir — not pulling, only welcoming. Warmth begins to wake.", "Invite, don't force."], ["Feel warmth begin to rise, vertebra by vertebra.", 70, "Feel a gentle heat climbing, one vertebra at a time, like dawn moving up a wall. Let it take its time.", "Follow the warmth as it climbs."], ["Let it rise toward the crown, unhurried.", 60, "Let the rising warmth move toward the crown, opening each centre it passes. Stay soft, stay curious.", "Keep the body relaxed as it rises."], ["Rest in the current. Let it settle on its own.", 40, "Now stop guiding it. Rest in the living current you've woken, and let it settle wherever it wishes.", "Let it find its own level."], ["Seal the practice. Breathe normally, and ground.", 16, "Take a few normal breaths. Feel the feet, the seat. Let the energy settle quietly within you.", "Feel grounded, calm, awake."]] },
      { id: "astral", t: "The Boundless Visualization", i: "\u2728", d: "A journey beyond the edges of the body.", kind: "guided", sound: "cosmos", log: "hc_logs", defMin: 15,
        phases: [["Lie or sit. Let the body grow heavy and still.", 30, "Let the body settle completely, heavy and still. For these minutes, you may set it down like a coat at the door.", "Let the body become quiet."], ["Feel the edges of the body soften and blur.", 60, "Notice the outline of the body — then let it blur. Where exactly does 'you' end and the air begin? Let the border soften.", "Let your edges grow vague."], ["Imagine awareness lifting, weightless, just above you.", 80, "Imagine your awareness floating up, light as warm smoke, hovering gently just above the resting body.", "Float. Nothing holds you down."], ["Expand outward — the room, the sky, the dark between stars.", 80, "Now widen — beyond the room, beyond the rooftops, up past the clouds, into the vast quiet dark between the stars.", "Keep expanding. There is no edge."], ["You are vast, boundless, and held by everything.", 60, "Feel how large you've become — spacious, boundless, and yet completely held by the whole of it. You belong to all of it.", "You are vast. You are held."], ["Begin to gather, slowly returning toward the body.", 50, "Slowly begin to draw the vastness back in, gathering yourself, drifting gently down toward the waiting body.", "Drift home, unhurried."], ["Return fully. Feel the weight, the breath, the ground.", 24, "Settle back fully into the body. Feel its comforting weight, the breath, the ground. You carry the vastness inside now.", "Welcome back. You are larger now."]] },
    ],
    heart: [
      { id: "open_heart", t: "Opening the Heart", i: "\uD83D\uDC9E", d: "Soften what's guarded.", kind: "guided", sound: "choir", log: "hc_logs", defMin: 8,
        phases: [["Place one hand over the centre of your chest.", 22, "Bring a hand to rest over the heart. Feel its warmth, and the faint, faithful beating beneath your palm.", "Feel your own heartbeat under your hand."], ["Breathe into the warmth beneath your hand.", 34, "Let each breath flow into that warmth, as if the chest could breathe directly. Let it widen, just a little.", "Breathe into your hand."], ["Recall a moment you felt truly, simply loved.", 50, "Call back one moment when you felt completely loved — a face, a place, a touch. Let it grow vivid and near.", "Who comes to mind? Let them be here."], ["Let that feeling fill the chest and brim over.", 46, "Let the warmth of that memory swell in the chest until it brims, soft and golden, filling more than your body.", "Let the warmth overflow."], ["Now turn it gently toward yourself.", 44, "Now let some of that love turn back toward you — the one breathing here. You, too, deserve this tenderness.", "Offer yourself the same love."], ["Let the guard you didn't know you held soften.", 40, "Notice any armour around the heart, and let it loosen — not torn away, just quietly set down. You are safe.", "Let something guarded soften."], ["Carry this open warmth with you.", 14, "Let the hand rest a moment more. Then carry this open, unguarded warmth gently into the rest of your day.", "Keep the heart this open."]] },
      { id: "forgive_self", t: "Self-Forgiveness", i: "\uD83C\uDF15", d: "Lay down a weight.", kind: "guided", sound: "choir", log: "hc_logs", defMin: 7,
        phases: [["Settle, and let one weight you carry come to mind.", 30, "Breathe, and let one thing you've been carrying rise gently — a regret, a harshness toward yourself. Just name it softly.", "Name, gently, what you carry."], ["Meet it without flinching, the way you'd meet a child.", 40, "Look at it the way you'd look at a frightened child — not with judgement, but with patience and a wish to understand.", "Soften your gaze toward yourself."], ["Say, inwardly: I did what I knew, with what I had.", 40, "Say it inwardly, and mean it kindly: I did what I knew how to do then, with what I had then. That is human.", "Inhale: 'I did what I knew.'"], ["Say: I am allowed to learn, and to grow.", 40, "And now: I am allowed to have learned. I am allowed to grow. The person who erred is not the whole of me.", "Exhale: 'I am allowed to grow.'"], ["Feel the weight grow lighter in your hands.", 40, "Feel the thing you've carried grow lighter, as if you could finally open your hands and let some of it go.", "Let your hands, and shoulders, drop."], ["Offer yourself the forgiveness you'd give a friend.", 36, "Give yourself the same forgiveness you would offer a dear friend without a second thought. You have earned it too.", "Forgive yourself, as you would a friend."], ["Rest, lighter. Carry the mercy forward.", 14, "Rest a moment in this lightness. Then carry this mercy with you — it is yours to keep.", "Walk on, a little lighter."]] },
    ],
    couple: [
      { id: "sync_breath", t: "Synced Breathing", i: "\uD83E\uDEC1", d: "Breathe as one.", kind: "guided", sound: "flute", log: "cp_logs", defMin: 8, breath: [5, 1, 6, 1],
        phases: [["Sit facing each other, close enough to feel near.", 24, "Sit facing one another, close enough that you can sense their presence. Let your eyes soften, or gently close.", "Settle. Feel them near you."], ["Rest a hand on your own chest, and feel your breath.", 30, "Place a hand on your own chest and find your breath, just as it is. Let it slow, without any effort.", "Find your own rhythm first."], ["Now listen for their breath, and let yours drift toward it.", 50, "Now sense the other's breathing — the rise and fall of them — and let your own breath drift, slowly, toward theirs.", "Listen for their rhythm."], ["Inhale together … and exhale together.", 70, "Breathe in together … and out together. Two separate lives, for this moment, moving as one quiet tide.", "In together … out together."], ["Feel the single rhythm that forms between you.", 60, "Notice the single shared rhythm that has appeared between you — something neither of you is making alone.", "One breath, shared between two."], ["Let the breath carry a silent wish to them.", 44, "On each exhale, let your breath carry a silent, wordless wish of care toward them. Let them feel held by it.", "Send them warmth on the breath."], ["Rest in the closeness you've made. Then open the eyes.", 18, "Rest in this closeness a little longer. When you're ready, open your eyes and meet theirs, softly.", "Open your eyes. See them anew."]] },
      { id: "gratitude_x", t: "Gratitude Exchange", i: "\uD83C\uDF1F", d: "Speak what you treasure.", kind: "guided", sound: "choir", log: "cp_logs", defMin: 6,
        phases: [["Sit close. Decide who will speak first, who will receive.", 24, "Sit close, and gently decide: one of you will speak first, the other will simply receive. You'll switch soon.", "One speaks. One receives. No rush."], ["Speaker: name one thing you're grateful for in them.", 54, "Speaker, look at them and name one thing you treasure about them — not grand, but true. Let your voice be soft.", "Be specific. Small is sacred."], ["Receiver: take it in. Do not deflect or downplay.", 50, "Receiver, your only task is to let it land. No joking it away, no deflecting. Just breathe, and let yourself be appreciated.", "Let it in. Just say 'thank you.'"], ["Now switch. The other speaks; the first receives.", 54, "Now gently switch. The other speaks their gratitude, and the first one simply receives it, fully.", "Switch. Speak from the heart."], ["Let what you each said settle between you.", 40, "Let the words you've exchanged settle in the space between you, like warmth in a held cup.", "Feel what's grown between you."], ["Thank each other for being heard, and end softly.", 18, "Thank one another — for speaking, and for listening. Let a small smile close the practice.", "Hold their gaze. Smile."]] },
      { id: "gazing", t: "Eye Gazing", i: "\uD83D\uDC41", d: "Be seen, and see.", kind: "guided", sound: "tanpura", log: "cp_logs", defMin: 6,
        phases: [["Sit close. Let your gaze rest softly in theirs.", 30, "Sit facing them, and let your gaze settle gently into one of their eyes — not staring, just resting there.", "Soften your eyes. Don't perform."], ["Let it feel awkward first. Breathe through it.", 50, "It may feel strange, even funny, at first. That's alright. Keep breathing slowly, and let the awkwardness pass through.", "Breathe. Let the awkwardness pass."], ["Let the gaze settle. There is nothing to do.", 70, "As you stay, something settles. There is nothing to perform here, nothing to say. Just two people, truly seeing.", "Nothing to do but be seen."], ["See them — not the role, the person.", 60, "Look past the everyday face into the person behind it — the same soul you first met. Let yourself really see them.", "Who is really there, behind their eyes?"], ["Let yourself be seen in return.", 50, "Now let yourself be seen, fully, without hiding. To be looked at this kindly is its own quiet gift.", "Let them see you, too."], ["Offer a small, true smile, and close.", 20, "When it feels complete, offer a small, genuine smile. Let it close the space gently between you.", "Smile. You found each other."]] },
      { id: "appreciations", t: "Three Appreciations", i: "\uD83D\uDC91", d: "End the day in praise.", kind: "guided", sound: "choir", log: "cp_logs", defMin: 5,
        phases: [["Sit together. Bring the day gently to mind.", 24, "Sit close and let the day replay softly — the small moments you shared, the ones that almost slipped by.", "Recall the small moments of today."], ["Each will name three things about the other, today.", 30, "In turn, you'll each name three things you appreciated about the other today. Three small, true things.", "Three things. Specific ones."], ["First speaker: offer your three. Be specific.", 54, "First one, speak your three appreciations slowly, letting each one fully land before the next. Small is sacred.", "Say what you noticed. Mean it."], ["Switch. The other offers their three.", 54, "Now switch. The other names their three, just as slowly, just as truly. Let them be received.", "Switch. Speak gently."], ["Receive each one fully, without deflecting.", 36, "As you're praised, resist brushing it off. Let each appreciation settle in, like a small light placed in your hands.", "Let each one in."], ["Thank each other, and let the day close in warmth.", 18, "Thank one another for seeing, and being seen. Let the day close wrapped in this small, shared warmth.", "End the day in praise."]] },
    ],
        awakening: [
      { id: "presence", t: "Pure Presence", i: "\u2728", d: "Drop into now.", kind: "guided", sound: "om", log: "hc_logs", defMin: 8,
        phases: [["Stop, just for a moment. Notice that you are here.", 24, "Let everything pause. Before the next thought, simply notice the bare fact that you exist, right now.", "You are here. Notice that."], ["What is present, before you name it?", 34, "What is actually here, before the mind labels anything? Sound, light, the weight of the body. Meet it raw.", "Drop the words. Meet what's here."], ["Sounds arise, sensations arise — and you are aware of them.", 44, "Sounds come and go. Sensations rise and fade. And something quietly knows all of it. That knowing is you.", "Notice what is aware of all this."], ["You are not the thoughts. You are the space they appear in.", 50, "Thoughts drift across you like birds across a sky. You are not the birds. You are the open sky they cross.", "You are the awareness, not the content."], ["Rest as that awareness — effortless, already here.", 54, "There is nothing to reach for. The awareness you seek is the very thing that is seeking. Rest as it.", "Nothing to do. Already here."], ["Let even the watching relax into pure being.", 44, "Let go of even watching. Just be — wordless, wide, present. This is your most ordinary, original nature.", "Simply be."], ["Stay a while in this simple presence.", 30, "Stay here, in this plain and perfect presence, as long as the breath wishes.", ""], ["Carry this 'now' with you as you return.", 14, "Slowly return, knowing this presence is always here, one breath away, whenever you stop to notice.", "It's always one breath away."]] },
      { id: "witness", t: "The Witness", i: "\uD83D\uDC41", d: "Watch the watcher.", kind: "guided", sound: "voidd", log: "hc_logs", defMin: 8,
        phases: [["Sit easy. Let the eyes close. Let the breath be.", 24, "Settle, and let the breath move on its own. We will look not at thoughts, but at the one who sees them.", "Let the breath breathe itself."], ["Notice a thought arise — then notice that you noticed.", 40, "Wait for a thought, and let it come. Now — notice that you noticed it. Something was watching. Turn toward that.", "A thought came. What saw it?"], ["Turn attention back toward the one who is aware.", 50, "Gently turn attention back on itself, toward the awareness reading every experience. Look for the looker.", "Look back at the watcher."], ["Can you find an edge to this awareness?", 54, "Search for a boundary to awareness — a wall, an edge, a centre. You will not find one. It is open, and vast.", "Find the edge. There is none."], ["The witness has no shape, yet all appears in it.", 50, "This witnessing has no shape, no location, no age — yet every sight and sound appears within it. It is the space of you.", "Everything appears in you."], ["Abide as the witness. Let all else come and go.", 54, "Rest as that open witnessing. Let thoughts, feelings, sensations arrive and depart. You remain, unchanged.", "You remain. Let the rest move."], ["Rest where there is no edge, and no centre.", 40, "Abide here, where there is no edge and no centre — only clear, knowing presence. This is what you are.", ""], ["Gently return, carrying the spaciousness.", 14, "When you are ready, return softly, keeping a little of this spaciousness with you.", "Stay a little spacious."]] },
      { id: "atma_vichara", t: "Self-Inquiry", i: "\uD83E\uDE94", d: "Who am I? \u2014 the path of Ramana.", kind: "guided", sound: "tanpura", log: "hc_logs", defMin: 12,
        phases: [["Sit quietly. Let the question rise: who am I?", 34, "Sit in stillness and let one question form, softly, without urgency: who am I? Do not answer it yet — just hold it.", "Ask, silently: who am I?"], ["Not this body — who is aware of the body?", 60, "You have a body, but you are aware of it, so you cannot only be it. Who is the one that is aware?", "Not the body. Who knows it?"], ["Not these thoughts — who watches them pass?", 60, "You have thoughts, but you watch them come and go. Who is the watcher that remains when a thought has gone?", "Not the thoughts. Who watches?"], ["When a thought arises, ask: to whom does this come?", 80, "Each time a thought appears, gently inquire: to whom has this come? To me. And then turn: and who am I?", "To whom? To me. And who am I?"], ["Follow the sense of 'I' back toward its source.", 80, "Do not chase the answer in words. Follow the very feeling of 'I' inward, back toward the place it rises from.", "Trace the 'I' to its root."], ["Rest where the 'I'-thought dissolves.", 70, "As you near the source, the separate 'I' grows quiet and dissolves. Rest there, in the silence it leaves behind.", "Rest where 'I' dissolves."], ["Abide as the 'I am' that remains.", 54, "What remains when the questioning stops is a simple, wordless sense of being — I am. Abide as that. That is you.", "Abide as 'I am'."], ["Return gently, the question still glowing.", 16, "Return slowly, carrying the quiet of this inquiry. The question will keep working in you, like a glowing ember.", "Carry the question with you."]] },
      { id: "shadow", t: "Meeting the Shadow", i: "\uD83C\uDF11", d: "Befriend what you have disowned.", kind: "guided", sound: "voidd", log: "hc_logs", defMin: 12,
        phases: [["Settle. Let the breath grow slow and safe.", 30, "Make yourself steady and safe. We will meet a hidden part of you with kindness, not judgement.", "Breathe. You are safe to look."], ["Recall a trait in others that strongly disturbs you.", 50, "Bring to mind a quality in other people that truly irritates or repels you — something you would never claim as yours.", "What in others truly bothers you?"], ["Ask, gently: where does this live in me, too?", 70, "Now ask, without flinching: where does a seed of this same thing live in me? The strongest charges often point home.", "Where does this live in me, too?"], ["Let the disowned part show its face.", 70, "Let that hidden part step forward and be seen. It may feel young, ashamed, or angry. Do not turn away from it.", "Let it show itself. Don't recoil."], ["Do not judge it — it was protecting you once.", 70, "Whatever it is, it formed long ago to protect you. Meet it the way you would meet a frightened child — with patience.", "It was trying to keep you safe."], ["Offer it understanding, and a place to belong.", 64, "Offer it understanding. Tell it, inwardly, that it belongs, that it no longer has to hide in the dark.", "Welcome it home."], ["Feel yourself become more whole as it is welcomed.", 50, "As it is received, feel a quiet wholeness return — the energy it held is yours again now, integrated and free.", "Feel yourself grow more whole."], ["Return, more complete than you began.", 16, "Return gently, carrying this part with you in the light. You are more complete for having met it.", "You are more whole now."]] },
      { id: "parts", t: "Parts Work", i: "\uD83E\uDDE9", d: "Turn toward the parts of you.", kind: "guided", sound: "choir", log: "hc_logs", defMin: 12,
        phases: [["Close the eyes. Sense the parts of you present today.", 34, "Let the eyes close. Notice that 'you' is made of many parts — and one or two are loud today. Sense them.", "Which part is loud right now?"], ["Find one part — anxious, critical, or sad.", 54, "Choose one active part — perhaps anxious, harshly critical, or quietly sad. Locate where it sits in the body.", "Where do you feel it in the body?"], ["Turn toward it with curiosity, not war.", 70, "Turn toward it with genuine curiosity, not as an enemy to defeat. Simply be interested in it, the way a friend would.", "Curiosity, not war."], ["Ask what it fears would happen if it stopped.", 80, "Ask it, kindly: what are you afraid would happen if you stopped doing your job? Then listen, without arguing.", "Ask what it fears. Then listen."], ["Thank it for how hard it has worked to protect you.", 70, "Thank this part. For years it has worked so hard, in its own way, to keep you safe. Let it feel appreciated.", "Thank it for trying."], ["Let it know you are here now, leading with calm.", 64, "Let it know that you — the calm, grown self at the centre — are here now, and it can finally rest.", "You are here now. It can rest."], ["Feel the system settle around a calm centre.", 50, "Feel the inner family settle, gathering around that calm centre. There is more space in you now.", "Feel the calm at your centre."], ["Return, holding all your parts with care.", 16, "Return slowly, holding every part of you with the same care. You contain multitudes — and you can lead them gently.", "Lead yourself, gently."]] },
      { id: "muraqaba", t: "Heart Watching", i: "\uD83D\uDD4C", d: "Sufi muraqaba \u2014 silent communion.", kind: "guided", sound: "ney", log: "hc_logs", defMin: 12,
        phases: [["Sit in stillness. Rest attention in the heart.", 34, "Sit as if before the Beloved. Let attention sink from the busy head down into the quiet centre of the chest.", "Let attention rest in the heart."], ["Let the breath grow soft and devotional.", 50, "Let each breath become a soft remembrance, slow and reverent, as though the heart itself were breathing.", "Breathe from the heart."], ["Imagine the divine gaze resting upon your heart.", 80, "Sense a gentle, loving gaze — the divine presence — resting upon your heart. You are seen, completely, and held.", "You are seen, and held."], ["Be watched, and watch — a wordless communion.", 80, "Rest in this two-way gaze: you, attentive to the Presence; the Presence, attentive to you. No words are needed.", "A wordless communion."], ["Let your separate self grow quiet.", 70, "Let the small, separate self grow faint, the way a candle pales at dawn. Less of 'you'; more of the Presence.", "Let the self grow faint."], ["Dissolve into the warmth. Only presence remains.", 70, "Let the heart melt into that warmth, until the watcher and the watched are one, and only Presence remains.", "Only presence remains."], ["Rest in nearness, beyond all asking.", 44, "Abide in this nearness — nothing to ask for, nothing to do — simply to be with, and in, the Beloved.", ""], ["Return softly, the heart still glowing.", 16, "Return gently to the room, carrying the heart's warmth like a lamp you can keep lit all day.", "Keep the heart's lamp lit."]] },
      { id: "sedona", t: "The Release", i: "\uD83C\uDF43", d: "Could I let this go? Could I, now?", kind: "guided", sound: "bowls", log: "hc_logs", defMin: 10,
        phases: [["Settle. Bring to mind something you are holding.", 30, "Settle in. Let one thing you have been gripping come forward — a worry, a wanting, a tightness. Feel it fully.", "Welcome the feeling fully."], ["Allow the feeling to be here, completely.", 50, "Do not fix it or explain it. Simply allow the feeling to be here, as much as it already is. Make room for it.", "Let it be exactly as it is."], ["Ask: could I let this go?", 60, "Now ask yourself, gently: could I let this go? It is only a question. Yes or no, both are fine. Just ask.", "Could I let this go?"], ["Ask: would I let it go?", 60, "And ask: would I let it go? Am I willing? Again, simply notice your honest answer, without forcing anything.", "Would I? Am I willing?"], ["Ask: when? And why not — now?", 60, "And finally: when? If not now, when? Let the holding loosen, even slightly, in this very moment.", "When, if not now?"], ["Let it go. Feel the space that opens.", 54, "Let it release, like an open hand letting a bird fly. Feel the small spaciousness that opens where it was.", "Open the hand. Feel the space."], ["Whatever returns, simply release again.", 44, "If it returns — and it may — simply welcome it, and release again. Each round, a little lighter.", "It returns; you release again."], ["Rest in the lightness. Return when ready.", 16, "Rest in whatever lightness remains. Return when you are ready, carrying this freedom to let go.", "Carry the freedom to let go."]] },
      { id: "breathwork", t: "Conscious Breathwork", i: "\uD83C\uDF2C", d: "Let the breath move what is held.", kind: "guided", sound: "samudra", log: "hc_logs", defMin: 12,
        phases: [["Lie back. Begin to breathe a little fuller.", 30, "Lie back somewhere you can be free. Begin to breathe a little fuller than usual, through an open, relaxed mouth.", "Breathe fuller than usual."], ["Connect the breath — no pause between in and out.", 60, "Let the inhale flow straight into the exhale, and the exhale into the next inhale — one continuous, circular wave.", "No pause. Keep it circular."], ["Keep the rhythm soft and steady, like the sea.", 70, "Keep it soft and rhythmic, not forced. Like the sea — in and out, in and out. Let the body find its own pace.", "Soft, steady, like the sea."], ["Feeling may rise. Let it. Stay with the breath.", 80, "As you continue, emotion or sensation may rise — tingling, warmth, tears, release. Let it come. Keep breathing through it.", "Whatever rises, keep breathing."], ["Let the breath move what has been held.", 80, "Trust the breath to move what has been stored and stuck. You need not understand it. Just let it move, and pass.", "Let the breath carry it out."], ["Now slow the breath. Let it return to calm.", 60, "Gently begin to slow the breath now. Let it grow quiet and easy again, the wave settling into still water.", "Slow the wave. Let it still."], ["Rest in stillness. Let the body integrate.", 54, "Rest completely. Let the body absorb whatever moved. There is nothing more to do but lie here, renewed.", "Rest. Let it all settle."], ["Return slowly, gently, in your own time.", 16, "When you are ready, return in your own time — slowly, gently — carrying a lighter, more open body with you.", "Return light, and open."]] },
      { id: "maranasati", t: "Death Awareness", i: "\uD83C\uDF11", d: "Maranasati \u2014 the clarifying truth.", kind: "guided", sound: "bowls", log: "hc_logs", defMin: 10,
        phases: [["Sit. Breathe. Let the body be still.", 30, "Sit quietly and let the body still. We turn now to a truth the wise keep close — gently, and without fear.", "Settle. Breathe. Be still."], ["Remember, softly: this life will end.", 50, "Bring to mind, kindly, the simple fact: this life will end. Not today's worries — the whole of it, one day, complete.", "This life will end. Breathe with it."], ["Not morbid — clarifying. Feel this moment grow precious.", 70, "This is not morbid; it is clarifying. Held lightly, the truth of death makes the gift of this moment shine.", "Feel this moment grow precious."], ["In this light, what truly matters?", 80, "In the light of life's brevity, ask: what truly matters? What would you no longer postpone? What grudge seems small now?", "What truly matters, in this light?"], ["Let the small worries fall away.", 70, "Let the petty worries, the comparisons, the endless waiting — let them fall like dry leaves. They are not the point.", "Let the small things fall away."], ["Let death be a wise and gentle companion.", 60, "Let mortality walk beside you, not as a threat, but as a wise companion that keeps you honest, awake, and kind.", "Death, the wise companion."], ["Return to this breath, more alive.", 44, "Come back to this one breath — this single, irreplaceable breath — more awake for having remembered.", "This breath. You are alive now."], ["Carry this aliveness into your day.", 16, "Return gently, carrying this vivid aliveness with you. Let it make you brave, and tender, today.", "Live this day awake."]] },
      { id: "hesychasm", t: "Prayer of the Heart", i: "\u271D\uFE0F", d: "A sacred word, breathed into the heart.", kind: "guided", sound: "choir", log: "hc_logs", defMin: 12,
        phases: [["Rest attention in the heart. Breathe slowly.", 34, "Sit in stillness and let attention descend from the head into the heart. Breathe slowly, as if before an altar.", "Bring the mind into the heart."], ["Choose a sacred word or holy name.", 50, "Choose a short, sacred phrase or holy name — one that is sacred to you. Hold it gently in the heart.", "Hold your sacred word."], ["On the inhale, breathe the word into the heart.", 80, "On each inhale, breathe the sacred words gently down into the heart, as if planting them in warm soil.", "Inhale the Name into the heart."], ["On the exhale, let it settle deeper.", 80, "On each exhale, let the words sink deeper, and let everything else — noise, worry, striving — quietly fall away.", "Exhale; let it settle deeper."], ["Let the words grow quiet; their meaning remains.", 70, "In time, let the spoken words grow faint, until only their warmth and meaning remain, glowing in the heart.", "Let the words grow still."], ["Be still, and know. Abide in the heart.", 70, "Be still now, and simply know. Abide in the warm stillness of the heart, where the sacred and you are near.", "Be still, and know."], ["Rest in the prayer that prays itself.", 44, "Rest as the prayer begins to pray itself, breathing in you without effort, like a heartbeat of devotion.", "Let the prayer pray itself."], ["Return gently, the heart kept warm.", 16, "Return slowly to the room, keeping the heart's warmth lit, carrying this quiet prayer into the hours ahead.", "Keep the heart warm."]] },
      { id: "koan", t: "The Koan", i: "\u2753", d: "A question with no answer, to open you.", kind: "guided", sound: "bowls", log: "hc_logs", defMin: 10,
        phases: [["Sit. Receive the question, not an answer.", 30, "Sit with a straight, easy spine. I will offer a question — not to solve, but to hold, like a hot stone in the hand.", "Hold the question, don't solve it."], ["What was your face before your parents were born?", 60, "Here is the koan: what was your original face, before your parents were born? Let it land. Do not reach for meaning.", "Let the question sit in you."], ["Do not think it through. Let it sit, unsolved.", 80, "Resist the urge to figure it out. Logic cannot enter here. Let the question simply live in you, unanswered, alive.", "No thinking. Just hold it."], ["When the mind grasps for an answer, release.", 80, "Each time the mind lunges for a clever answer, notice, and let it go. Return, empty-handed, to the question.", "Release the answer. Return."], ["Let the question dissolve the one who asks.", 70, "Stay with it long enough and the question begins to work on you — loosening the very self that wants to know.", "Let it loosen the knower."], ["Rest in not-knowing. That openness is the point.", 60, "Rest in the open, spacious not-knowing the koan creates. That openness — not an answer — is the whole point.", "Rest in not-knowing."], ["Stay in the spaciousness it opens.", 40, "Abide here, in the wide, clear space the unsolved question has opened in you. Nothing to grasp. Just this.", ""], ["Return, carrying the open question.", 16, "Return gently, letting the question keep glowing in you. It will keep opening you, long after you rise.", "Carry the open question."]] },
    ],
    world: [
      { id: "zazen", t: "Zazen (Japan)", i: "\u26E9\uFE0F", d: "Zen seated meditation \u2014 just sitting.", kind: "guided", sound: "bowls", log: "hc_logs", defMin: 10,
        phases: [["Sit. Hands in the cosmic mudra, eyes soft and low.", 30, "Sit upright and dignified. Rest the hands in the cosmic mudra at the belly, eyes half-open, gaze soft upon the floor.", "Spine tall. Eyes soft and low."], ["Take three slow, deep breaths to arrive.", 34, "Take three deep, slow breaths to mark the beginning — long out-breaths — then let the breath return to natural.", "Three deep breaths. Arrive."], ["Breathe naturally. Count each exhale, one to ten.", 80, "Now breathe as the body wishes. Silently count each exhale — one, two, up to ten — then begin again at one.", "Count each exhale, one to ten."], ["When the count is lost, simply begin again.", 80, "When you realise the count has slipped or run past ten — and it will — return softly to one. No failure here.", "Lost the count? Begin again."], ["Let thoughts pass like clouds — do not follow.", 80, "Thoughts will drift through like clouds. Do not chase them, do not fight them. Let them cross the open sky of mind.", "Clouds passing. Let them go."], ["Now let even the counting fall away. Just sit.", 70, "Release even the counting. This is shikantaza — just sitting. Nothing added, nothing sought. Only this upright presence.", "Just sitting. Nothing added."], ["Sit as a mountain — still, vast, complete.", 44, "Sit like a mountain — unmoving, vast, already complete. There is nowhere to go and nothing to attain. You are here.", "Be the mountain. Complete."], ["Bow, gently, and return.", 14, "When you are ready, take a slow breath, offer a small inward bow of gratitude, and gently return.", "A small bow. Return."]] },
      { id: "taiji", t: "Qi Flow (China)", i: "\u262F\uFE0F", d: "Taoist microcosmic orbit.", kind: "guided", sound: "flute", log: "hc_logs", defMin: 11,
        phases: [["Sit, tongue lightly to the palate, breath slow.", 30, "Sit comfortably, spine soft and tall. Touch the tongue lightly to the upper palate — the bridge joining the two channels.", "Tongue to the palate. Breathe slow."], ["Gather warmth at the navel.", 44, "Bring gentle attention just below the navel — the lower dantian — and let a soft warmth gather there, like a coal.", "Feel warmth gather below the navel."], ["On the inhale, draw the warmth up the spine.", 80, "As you breathe in, draw that warm energy down to the base, then up the spine, vertebra by vertebra, toward the crown.", "Inhale: warmth rises up the spine."], ["At the crown, let it pause and brighten.", 60, "Let the warmth arrive at the crown and pause there a moment, gently brightening, like the sun at its zenith.", "Pause at the crown. Let it glow."], ["On the exhale, let it flow down the front.", 80, "As you breathe out, let the energy flow down the front — face, throat, chest — all the way back down to the navel.", "Exhale: it flows down the front."], ["Circle it — up the back, down the front.", 80, "Now let it circle — up the back on each inhale, down the front on each exhale — a slow, closed, gentle orbit.", "Up the back, down the front."], ["Let the orbit turn on its own.", 60, "Once the circle feels natural, stop directing it. Let the orbit turn by itself, warm and unhurried, and simply ride it.", "Let the circle turn itself."], ["Gather the warmth back at the navel. Seal it.", 30, "Finally, let the energy settle and gather again at the navel. Rest a hand there, sealing the warmth within. Then return.", "Gather it at the navel. Seal it."]] },
      { id: "tonglen", t: "Tonglen (Tibet)", i: "\uD83C\uDFD4\uFE0F", d: "Giving and taking, breath by breath.", kind: "guided", sound: "bowls", log: "hc_logs", defMin: 10,
        phases: [["Settle. Let the breath grow even and calm.", 30, "Sit and let the breath settle into an even, gentle rhythm. We practise taking in pain, and sending out relief.", "Even, calm breaths to begin."], ["Begin with yourself — a difficulty you carry.", 44, "Begin close to home. Bring to mind a difficulty you yourself are carrying right now. Let it be real, and present.", "Bring your own pain to mind."], ["On the inhale, breathe it in as warm dark smoke.", 80, "On the in-breath, breathe that suffering in as warm, dark smoke — not to keep it, but to transform it in the heart.", "Inhale the pain, as dark smoke."], ["On the exhale, breathe out relief, coolness, light.", 80, "On the out-breath, send out the opposite — cool, bright relief, spaciousness, ease — like moonlight from the heart.", "Exhale relief, cool and bright."], ["Take in the pain; send out ease. Breath by breath.", 80, "Continue, breath after breath — taking in the dark, sending out the light. Let the heart be where pain turns to peace.", "Dark in. Light out. Again."], ["Now widen it to all who suffer as you do.", 70, "Now widen the circle. Breathe in the same pain felt by countless others, and send relief to them all. You are not alone.", "Breathe for all who suffer so."], ["Let the heart grow vast enough to hold it all.", 60, "Let the heart grow vast — vast enough to take in the world's ache and answer with kindness. This is the awakened heart.", "Let the heart grow vast."], ["Rest, heart softened and open.", 16, "Rest now. Let the breath return to normal. Notice the heart — softened, opened, quietly brave. Carry it with you.", "Rest. The heart is open now."]] },
    ],
    pranayama: [
      { id: "box", t: "Box Breathing", i: "\uD83D\uDFE6", d: "Equal four-count breath \u2014 calm under pressure.", kind: "guided", sound: "flute", log: "hc_logs", defMin: 4, breath: [4, 4, 4, 4],
        phases: [["Sit tall, shoulders soft. We breathe in equal fours.", 24, "Sit tall and at ease. We will breathe in four equal counts — in, hold, out, hold — a square of calm you can use anywhere.", "Spine tall, shoulders soft."], ["Exhale fully to empty, and we begin.", 20, "First, breathe all the way out, emptying completely. Now follow the count, and let the glowing pacer guide you.", "Empty out, then follow the light."], ["Inhale… two, three, four.", 30, "Breathe in slowly through the nose — two, three, four — filling smoothly from the belly up to the chest.", "Inhale, two, three, four."], ["Hold… two, three, four.", 30, "Hold the breath gently — two, three, four — no strain at all, just a soft and full pause.", "Hold, two, three, four."], ["Exhale… two, three, four.", 30, "Release slowly — two, three, four — letting the breath leave as smoothly as it came in.", "Exhale, two, three, four."], ["Hold empty… two, three, four.", 30, "Rest in the empty pause — two, three, four — calm and unhurried. Then the square begins again.", "Hold empty, two, three, four."], ["Let the square breathe you. Calm and steady.", 54, "Now let the rhythm carry itself. The four equal sides hold you like the walls of a quiet room. Calm. Steady. Even.", "Let the square breathe you."], ["Release the count. Breathe freely. Notice the calm.", 24, "Let the count dissolve and breathe freely now. Notice the settled, level calm the practice has left in you.", "Free breath. Notice the calm."]] },
      { id: "b478", t: "4-7-8 Breath", i: "\uD83C\uDF19", d: "The natural tranquiliser for the nerves.", kind: "guided", sound: "flute", log: "hc_logs", defMin: 5, breath: [4, 7, 8, 1],
        phases: [["Rest the tongue tip behind the upper teeth.", 20, "Sit comfortably and rest the tip of the tongue just behind your upper front teeth, where it will stay throughout.", "Tongue behind the upper teeth."], ["Empty the lungs with a soft whoosh.", 20, "Begin by exhaling completely through the mouth, with a soft whoosh. Empty fully. Now we begin the cycle.", "Exhale fully. Whoosh."], ["Inhale through the nose… four.", 26, "Close the mouth and inhale quietly through the nose for a count of four. Smooth and gentle.", "Inhale, two, three, four."], ["Hold… seven.", 40, "Now hold the breath for seven. Stay relaxed — the hold is restful, not a strain. Let the stillness gather.", "Hold… to seven."], ["Exhale through the mouth… eight.", 44, "Exhale slowly through the mouth for eight, with that soft whoosh, letting tension drain out with the breath.", "Exhale, long, to eight."], ["Again — four in, seven hold, eight out.", 70, "Continue the cycle — in for four, hold for seven, out for eight. The long exhale is the medicine; let it lengthen.", "Four in, seven hold, eight out."], ["Feel the nervous system settle and slow.", 40, "With each round, feel the heart slow and the nerves quiet. This breath is a natural tranquiliser. Let it work.", "Feel the body downshift."], ["Let the breath return to normal. Rest.", 24, "Let the counting go now and breathe normally. Rest in the deep calm you have created. Notice how settled you feel.", "Normal breath. Deep calm."]] },
      { id: "nadi", t: "Nadi Shodhana", i: "\u262F\uFE0F", d: "Alternate nostril \u2014 balancing the channels.", kind: "guided", sound: "flute", log: "hc_logs", defMin: 6, breath: [4, 1, 4, 1],
        phases: [["Bring the right hand near the nose, fingers ready.", 26, "Sit tall. Raise the right hand; the thumb will close the right nostril, the ring finger the left. Rest the other fingers softly.", "Thumb and ring finger ready."], ["Close the right; inhale slowly through the left.", 40, "Close the right nostril with the thumb. Inhale slowly and smoothly through the left — calm, cool, unhurried.", "Right closed. Inhale left."], ["Close both a moment; gently switch.", 30, "Close both nostrils for the briefest pause, then release the right and seal the left with the ring finger.", "Pause. Now switch sides."], ["Exhale through the right; then inhale right.", 44, "Exhale slowly through the right nostril. Then inhale through that same right side, smooth and even.", "Exhale right, then inhale right."], ["Close the right; exhale left. That is one round.", 44, "Close the right again and exhale through the left. That completes one full round. Breathe it slowly, never rushing.", "Exhale left. One round done."], ["Continue, smooth and slow, balancing the channels.", 70, "Continue the alternating flow — left, right, left — feeling the two channels, sun and moon, come into quiet balance.", "Balance the sun and moon."], ["Feel the mind grow even and clear.", 40, "Notice how the breath evens the mind, like a hand smoothing water. Steady, centred, and clear.", "Feel the mind grow even."], ["Release the hand. Breathe freely. Feel the balance.", 30, "Lower the hand and breathe freely through both nostrils. Rest in the balanced, settled clarity you have created.", "Both sides open. Balanced."]] },
      { id: "ujjayi", t: "Ujjayi Ocean Breath", i: "\uD83C\uDF0A", d: "The victorious breath, sound of the inner sea.", kind: "guided", sound: "samudra", log: "hc_logs", defMin: 5, breath: [5, 0, 7, 0],
        phases: [["Breathe through the nose, mouth gently closed.", 26, "Sit tall and breathe only through the nose, lips softly sealed. We will give the breath the sound of the sea.", "Nose only. Lips softly closed."], ["Narrow the throat, as if fogging a mirror within.", 44, "Gently narrow the back of the throat — as if fogging a mirror, but with the mouth closed. A soft ocean hiss appears.", "Narrow the throat, softly."], ["Hear the ocean sound on the inhale.", 50, "As you breathe in for about five, hear that soft oceanic whisper rising — the tide flowing in across the sand.", "Inhale: the tide flows in."], ["And on the exhale — the tide drawing back.", 50, "Breathe out longer, for about seven, and hear the tide drawing slowly back. Keep the sound smooth and unbroken.", "Exhale: the tide draws back."], ["Let each breath be one long, smooth wave.", 70, "Let every breath become a single, long, smooth wave — in and out — the throat quietly singing its ocean song.", "One long wave, in and out."], ["Let the sound carry you, wave after wave.", 60, "Stop counting now. Let the sound itself carry you, wave after wave, rocking the mind into a steady, warm calm.", "Ride the waves. Let go."], ["Soften the throat. Return to silent breath.", 24, "Gently soften the throat and let the ocean fade back to silent, natural breathing. Rest in the calm it leaves.", "Let the ocean fade. Rest."]] },
      { id: "kapal", t: "Kapalabhati", i: "\uD83D\uDD25", d: "Skull-shining breath \u2014 the inner fire.", kind: "guided", sound: "tanpura", log: "hc_logs", defMin: 3,
        phases: [["Sit tall. This breath is active — sharp out, soft in.", 30, "Sit very tall, the belly free. Kapalabhati is forceful on the exhale only — a sharp pump from the belly — while the inhale falls in by itself.", "Sit tall. Belly free."], ["Try a few slow pumps first.", 30, "Try a few slowly: a quick, sharp contraction of the belly pushes the air out through the nose; then relax, and air slips back in.", "Sharp out. Let the inhale fall in."], ["Now find a steady, rhythmic pace.", 60, "Now build a steady rhythm of short, sharp exhales — about one each second — the belly pulsing like a soft drum.", "The belly pulses, steady."], ["Keep it light. Never strain.", 60, "Keep it light and easy. This is skull-shining breath, not force. If you feel dizzy, slow down or pause. Be kind to yourself.", "Light, never strained."], ["Complete a round, then breathe naturally.", 44, "Complete your round of pumping, then stop entirely. Let the breath return to normal, and simply watch it.", "Stop. Let the breath return."], ["Rest in the bright, clear, tingling space.", 40, "Rest now in the bright, clean, slightly tingling spaciousness the practice leaves behind — the skull, as it were, shining.", "Rest in the bright clear space."]] },
    ],
  };
  // purpose-specific continuation murmurs — woven through long sessions so the guide never leaves you in silence
  const MURMURS = {
    stillness:["Let it pass.","Return, gently.","Rest as the space.","Nothing to hold.","Just this breath.","Be the stillness."],
    bodyscan:["Let that part grow heavy.","Soften wherever you hold.","Nothing to do but feel.","Let the breath reach there.","Warm, and loose.","Melt, a little more."],
    soham:["So\u2026 on the in-breath.","Ham\u2026 on the out-breath.","Let it breathe you.","No effort now.","I am.","Just being."],
    nidra:["Heavier still.","Sinking, softly.","Awake, and at rest.","Let the body sleep.","Float here.","Nothing to carry."],
    vipassana:["Watch it rise.","Watch it pass.","Bare attention.","Nothing to fix.","It is changing.","Only knowing."],
    chakra:["Breathe into the light.","Let the centre open.","Glowing, softly.","Rising, gently.","Feel the warmth.","Steady and bright."],
    kundalini:["Invite, don't force.","Warmth, rising.","Vertebra by vertebra.","Stay soft.","Let it climb.","Settle on its own."],
    astral:["Wider still.","Weightless.","No edges now.","Held by everything.","Vast, and at peace.","Drifting, free."],
    open_heart:["Breathe into the warmth.","Let it overflow.","You deserve this too.","Soften the guard.","Let the heart open.","Tender, and safe."],
    forgive_self:["You did what you knew.","You're allowed to grow.","Lay it down.","Be gentle with you.","Lighter now.","Mercy, for yourself."],
    sync_breath:["Find their rhythm.","In together.","Out together.","One tide.","Feel them near.","Send them warmth."],
    gratitude_x:["Let it land.","Small is sacred.","Receive it fully.","No deflecting.","Just say thank you.","Feel it between you."],
    gazing:["Soften the eyes.","Nothing to perform.","Let it settle.","See them truly.","Let yourself be seen.","Stay, gently."],
    appreciations:["Three small things.","Be specific.","Let each one in.","Receive it.","Seen, and seeing.","End in warmth."],
    presence:["What is here, now?","Before thought.","You are the awareness.","Rest as that.","Just being.","This, exactly this."],
    witness:["Who notices?","Watch the watcher.","No edge to find.","Abide there.","Aware of awareness.","Rest as knowing."],
    atma_vichara:["Who am I?","To whom does this arise?","Trace the 'I' back.","Not the body, not the mind.","Rest at the source.","Abide as 'I am'."],
    shadow:["Where does this live in me?","Do not judge it.","Meet it gently.","It was protecting you.","Let it be seen.","Welcome it home."],
    parts:["Turn toward the part.","Curiosity, not war.","What does it want for you?","Thank it for trying.","You are here now.","Let it relax."],
    muraqaba:["Rest in the heart.","Under the divine gaze.","Be watched, and watch.","A wordless communion.","Dissolve into presence.","Only presence remains."],
    sedona:["Could I let this go?","Would I?","When? Why not now?","Let it go.","Feel the space open.","Whatever returns, release."],
    breathwork:["Keep it circular.","No pause between.","Let it move through you.","Whatever rises, breathe.","On the breath, release.","Now slow, and rest."],
    maranasati:["This life will end.","What truly matters?","Let the small fall away.","Death, the wise companion.","More alive, for remembering.","Return to this breath."],
    hesychasm:["Lord, have mercy.","The Name, on the breath.","Mind into the heart.","Let the words grow still.","Be still, and know.","Abide in the heart."],
    koan:["Don't think it through.","Sit with the question.","Release the answer.","Return to the koan.","Rest in not-knowing.","What is this?"],
    zazen:["Just sitting.","Count the exhale.","Begin again.","No failure here.","Thoughts pass like clouds.","Nothing to attain."],
    taiji:["Up the spine.","Down the front.","Let it circle.","Soft and slow.","The orbit turns.","Rest in the flow."],
    tonglen:["Breathe in the pain.","Breathe out relief.","Take in; send out.","For all who suffer so.","Dark in, light out.","Heart, softened."],
    box:["In, two, three, four.","Hold, two, three, four.","Out, two, three, four.","Hold empty, four.","The square breathes you.","Calm and steady."],
    b478:["In, for four.","Hold, for seven.","Out, for eight.","Soft and slow.","The nerves settle.","Again, gently."],
    nadi:["Close the right.","Inhale, left.","Close the left.","Exhale, right.","Balance the channels.","Smooth and slow."],
    ujjayi:["Hear the ocean.","Narrow the throat.","The tide comes in.","The tide draws back.","Wave after wave.","Carried by the sound."],
    kapal:["A sharp exhale.","Let the inhale fall in.","The belly pulses.","Light and steady.","Never strain.","Bright, clear space."],
    presence:["What is here, now?","Before thought.","You are the awareness.","Rest as that.","Just being.","This, exactly this."],
  };
  var ATR_MUR = ["Deeper in.","Trust the descent.","You are safe here.","Let it speak.","Stay, and witness.","Carry only what is yours.","Breathe, and cross."];

  function find(id) { for (const k in LIB) { const m = LIB[k].find((p) => p.id === id); if (m) return m; } return null; }

  function listScreen(name, title, cats, sub) {
    Router.register(name, function (root) {
      root.appendChild(topBar({ title: title, back: true }));
      const body = H.el("div", { class: "pad scroll grow stack reveal" });
      root.appendChild(body);
      if (sub) body.appendChild(H.el("p", { class: "center", style: "font-family:var(--f-soul);font-style:italic;color:var(--text-dim)" }, sub));
      cats.forEach((cat) => (LIB[cat] || []).forEach((p) => {
        body.appendChild(H.el("button", { class: "zone-card", onClick: () => {
          if (p.kind === "breath") return Router.go("breathe");
          if (p.kind === "metta") return Router.go("metta");
          Router.go("practice", { id: p.id });
        } }, [
          H.el("div", { class: "zc-icon" }, p.i),
          H.el("div", { class: "zc-body" }, [H.el("div", { class: "zc-title" }, p.t), H.el("div", { class: "zc-desc" }, p.d)]),
        ]));
      }));
      return {};
    });
  }
  listScreen("meditation", "Meditation Zone", ["meditation", "awakening"], "Guided journeys for the solitary soul.");
  listScreen("heart", "Heart-Centred", ["heart"], "Rituals to open and mend the heart.");
  listScreen("couple", "Couple Practices", ["couple"], "Done together, two as one.");

  // ── every practice runs through the shared Guide engine ──
  Router.register("practice", function (root, query) {
    var p = find(query && query.id);
    if (!p) { Router.go("meditation"); return {}; }
    root.appendChild(topBar({ title: p.t, back: true }));
    return Guide.mount(root, {
      title: p.t,
      sound: p.sound || "cosmos",
      defaultMin: p.defMin || 5,
      silence: p.kind === "silence",
      phases: p.phases || [],
      murmurs: MURMURS[p.id],
      breath: p.breath,
      log: p.log,
      getConv: function () { return APP.activeConv; },
    });
  });

  // ── ANTARYATRA — the seven-stage inner pilgrimage (restored from V1) ──
  // phase = [prompt(shown), baseSeconds, voice(narrated), question(reflection)]
  var ANTARYATRA = [
    ["Sit. Settle into your body. Feel the weight of your hands. The pilgrimage begins not when you move, but when you arrive.", 120,
     "Welcome, traveller. The journey begins here, with the simple act of arriving in your own skin.",
     "What did you bring with you? What did you leave at the door?"],
    ["Your breath is a bridge between worlds. The outer world fades on the inhale. The inner world opens on the exhale. Cross slowly.", 120,
     "Breathe deeply now. Each breath is a step. The world outside grows distant. The world within draws near.",
     "On this side of the bridge, what grows quiet? What grows clearer?"],
    ["Step into the chamber of your heart. Light a candle in its centre. Sit on the floor. Whatever has been waiting here, let it speak.", 120,
     "You enter the heart chamber now. Sacred. Tender. You are safe here. What waits for you?",
     "What is the heart holding that you have been refusing to see?"],
    ["Walk through the forest of your memories. Do not stop at any one tree. Just notice which ones bloom in late season, and which stand bare.", 130,
     "The memory forest is vast. Walk among the trees. Some bloom. Some are winter-stripped. Both are sacred.",
     "Which memory tugged at your sleeve, asking to be held one more time?"],
    ["Descend now into the ocean within. Do not fear the depth. Things live here that have always loved you. You are not alone in your own darkness.", 130,
     "Down now. Into the deep. Trust the descent. What lives here is part of you. It has been waiting.",
     "What feeling rose from the deep, that you usually keep buried?"],
    ["Now meet yourself. Not the role. Not the mask. The witness behind your own eyes. Sit across from them. Look without flinching.", 130,
     "Here, you meet yourself. The one behind all the others. They have been waiting longer than you know.",
     "What did they want to tell you, that no one else has been able to?"],
    ["Begin the journey back now. Carry only what is yours. Leave what you released. Move slowly upward, toward the world. The threshold approaches.", 130,
     "Now the return. Slowly. Gently. Carry what you found. The world is waiting, but unhurried. You are different now.",
     "What is one word you bring back with you?"],
  ];
  var ATR_STAGES = [
    { name: "Prarambha · The Beginning", icon: "🌑", color: "#E2C28A", visual: "breath", sound: "om" },
    { name: "Shvasa-Setu · Bridge of Breath", icon: "🌒", color: "#E8009A", visual: "bridge", sound: "flute" },
    { name: "Hridayasthala · The Heart Place", icon: "🌓", color: "#FF6088", visual: "heart", sound: "choir" },
    { name: "Smriti-Vana · Memory Forest", icon: "🌔", color: "#A8D8B9", visual: "forest", sound: "bowls" },
    { name: "Antar-Sagar · The Inner Ocean", icon: "🌕", color: "#5B8FB9", visual: "ocean", sound: "samudra" },
    { name: "Atmadarshan · The Soul Witness", icon: "🌖", color: "#C9A96E", visual: "mirror", sound: "tanpura" },
    { name: "Punaragama · The Return", icon: "🌗", color: "#FFD480", visual: "rise", sound: "choir" },
  ];
  Router.register("antaryatra", function (root) {
    root.appendChild(topBar({ title: "Antaryatra", back: true }));
    return Guide.mount(root, {
      title: "Antaryatra · Inner Pilgrimage",
      sound: "cosmos", defaultMin: 14, minutes: [7, 10, 14, 20, 30],
      phases: ANTARYATRA, stages: ATR_STAGES, murmurs: ATR_MUR, log: "hc_logs",
    });
  });

  window.PRACTICE_LIB = LIB;
})();
