/* ============================================================
 * SPURANA · core/ambient.js — V1's authentic AMB soundscapes.
 * Generative per-world audio restored from Spurana V1: rain +
 * thunder, fire crackle, ocean swell, forest birdsong, temple
 * bells, baul vibrato, cosmos pads, aurora shimmer… Adapted to
 * the Ambient interface (enable/setPreset/setVolume). Off by
 * default; user-gesture started; persisted.
 * ============================================================ */
window.Ambient = (function () {
  "use strict";
  const KEY = "spurana.ambient";
  let enabled = false, vol = 0.3, preset = "cosmos";
  function load() { try { const v = JSON.parse(localStorage.getItem(KEY) || "{}"); if (typeof v.on === "boolean") enabled = v.on; if (typeof v.vol === "number") vol = v.vol; } catch (e) {} }
  function save() { try { localStorage.setItem(KEY, JSON.stringify({ on: enabled, vol: vol })); } catch (e) {} }

  const AMB = {
    _ctx: null, _nodes: [], _mg: null,
    _c() { if (!this._ctx) this._ctx = new (window.AudioContext || window.webkitAudioContext)(); if (this._ctx.state === "suspended") this._ctx.resume(); return this._ctx; },
    stop() { this._nodes.forEach((n) => { try { n.stop ? n.stop() : n(); } catch (e) {} }); this._nodes = []; if (this._mg) { try { this._mg.gain.setTargetAtTime(0, this._c().currentTime, 0.5); } catch (e) {} } },
    play(env) {
      if (!enabled) return; this.stop();
      try {
        const c = this._c(); this._mg = c.createGain(); this._mg.gain.setValueAtTime(0, c.currentTime); this._mg.gain.linearRampToValueAtTime(vol, c.currentTime + 2.5);
        try { const conv = c.createConvolver(); conv.buffer = this._impulse(c); const wet = c.createGain(); wet.gain.value = 0.5; const dry = c.createGain(); dry.gain.value = 0.85; this._mg.connect(dry); dry.connect(c.destination); this._mg.connect(conv); conv.connect(wet); wet.connect(c.destination); } catch (e) { this._mg.connect(c.destination); }
        ({ borsha: () => this._rain(c), bajra: () => this._storm(c), agni: () => this._fire(c), samudra: () => this._ocean(c), himalaya: () => this._wind(c), aranya: () => this._forest(c), lava: () => this._lava(c), cosmos: () => this._cosmos(c), mandir: () => this._mandir(c), aurora: () => this._aurora(c), dhoop: () => this._dhoop(c), chandra: () => this._chandra(c), raat: () => this._raat(c), baul: () => this._baul(c), nodi: () => this._nodi(c), padma: () => this._padma(c), sandhya: () => this._sandhya(c), sundarban: () => this._forest(c), kantha: () => this._kantha(c), grahan: () => this._grahan(c), sakura: () => this._sakura(c), desert: () => this._desert(c), om: () => this._om(c), choir: () => this._choir(c), bowls: () => this._bowls(c), flute: () => this._flute(c), ney: () => this._ney(c), tanpura: () => this._tanpura(c), voidd: () => this._void(c) }[env] || (() => this._cosmos(c)))();
      } catch (e) {}
    },
    _noise(c, type) { const sz = c.sampleRate * 3, buf = c.createBuffer(1, sz, c.sampleRate), d = buf.getChannelData(0); let L = 0; for (let i = 0; i < sz; i++) { const w = Math.random() * 2 - 1; if (type === "pink") { L = (L + 0.02 * w) / 1.02; d[i] = L * 3.5; } else if (type === "brown") { L = (L + 0.02 * w) / 1.02; d[i] = L * 14; } else d[i] = w; } const s = c.createBufferSource(); s.buffer = buf; s.loop = true; return s; },
    _bf(c, type, freq, Q) { const f = c.createBiquadFilter(); f.type = type; f.frequency.value = freq; f.Q.value = Q || 1; return f; },
    _rain(c) { [[3200, 0.4], [1200, 0.15], [6000, 0.18]].forEach(([f, v]) => { const s = this._noise(c), b = this._bf(c, "bandpass", f, 0.8), g = c.createGain(); g.gain.value = v; s.connect(b); b.connect(g); g.connect(this._mg); s.start(); this._nodes.push(s); }); this._thunder(c, true); },
    _storm(c) { this._rain(c); },
    _thunder(c, soft) { const delay = soft ? 15000 + Math.random() * 30000 : 8000 + Math.random() * 20000; const t = setTimeout(() => { try { const o = c.createOscillator(), g = c.createGain(); o.type = "sawtooth"; o.frequency.value = 70; o.frequency.exponentialRampToValueAtTime(30, c.currentTime + 0.6); g.gain.setValueAtTime(0.5, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 1.8); o.connect(g); g.connect(this._mg); o.start(); o.stop(c.currentTime + 1.8); } catch (e) {} this._thunder(c, soft); }, delay); this._nodes.push(() => clearTimeout(t)); },
    _fire(c) { const s = this._noise(c, "pink"), hp = this._bf(c, "highpass", 600), lp = this._bf(c, "lowpass", 3500), g = c.createGain(); g.gain.value = 0.3; s.connect(hp); hp.connect(lp); lp.connect(g); g.connect(this._mg); s.start(); this._nodes.push(s); const crk = () => { try { const o = c.createOscillator(), g2 = c.createGain(); o.type = "square"; o.frequency.value = 200 + Math.random() * 500; g2.gain.setValueAtTime(0.1, c.currentTime); g2.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.07); o.connect(g2); g2.connect(this._mg); o.start(); o.stop(c.currentTime + 0.07); } catch (e) {} const t = setTimeout(crk, 80 + Math.random() * 350); this._nodes.push(() => clearTimeout(t)); }; crk(); },
    _ocean(c) { const s = this._noise(c, "brown"), lfo = c.createOscillator(), lg = c.createGain(), bp = this._bf(c, "bandpass", 500, 0.4), g = c.createGain(); lfo.frequency.value = 0.1; lg.gain.value = 0.35; g.gain.value = 0.45; lfo.connect(lg); lg.connect(g.gain); s.connect(bp); bp.connect(g); g.connect(this._mg); s.start(); lfo.start(); this._nodes.push(s, lfo); },
    _wind(c) { const s = this._noise(c, "white"), hp = this._bf(c, "highpass", 300), lfo = c.createOscillator(), lg = c.createGain(), g = c.createGain(); lfo.frequency.value = 0.05; lg.gain.value = 0.22; g.gain.value = 0.22; lfo.connect(lg); lg.connect(g.gain); s.connect(hp); hp.connect(g); g.connect(this._mg); s.start(); lfo.start(); this._nodes.push(s, lfo); },
    _forest(c) { const bird = () => { try { const o = c.createOscillator(), g = c.createGain(), f = 1100 + Math.random() * 1600; o.type = "sine"; o.frequency.value = f; o.frequency.exponentialRampToValueAtTime(f * 1.6, c.currentTime + 0.12); g.gain.setValueAtTime(0.05, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 0.4); o.connect(g); g.connect(this._mg); o.start(); o.stop(c.currentTime + 0.4); } catch (e) {} const t = setTimeout(bird, 600 + Math.random() * 3500); this._nodes.push(() => clearTimeout(t)); }; bird(); const s = this._noise(c, "pink"), lp = this._bf(c, "lowpass", 500), g = c.createGain(); g.gain.value = 0.07; s.connect(lp); lp.connect(g); g.connect(this._mg); s.start(); this._nodes.push(s); },
    _lava(c) { [40, 55, 70].forEach((f) => { const o = c.createOscillator(), g = c.createGain(), lfo = c.createOscillator(), lg = c.createGain(); o.type = "sawtooth"; o.frequency.value = f; lfo.frequency.value = 0.25; lg.gain.value = 0.06; lfo.connect(lg); lg.connect(g.gain); g.gain.value = 0.08; o.connect(g); g.connect(this._mg); o.start(); lfo.start(); this._nodes.push(o, lfo); }); },
    _cosmos(c) { [136.1, 272.2, 204.15].forEach((f, i) => { const o = c.createOscillator(), g = c.createGain(); o.type = "sine"; o.frequency.value = f; g.gain.value = [0.04, 0.02, 0.03][i]; o.connect(g); g.connect(this._mg); o.start(); this._nodes.push(o); }); },
    _mandir(c) { this._cosmos(c); const bell = () => { try { const o = c.createOscillator(), g = c.createGain(); o.type = "sine"; o.frequency.value = 440 * Math.pow(2, Math.floor(Math.random() * 5 - 2) / 12); g.gain.setValueAtTime(0.14, c.currentTime); g.gain.exponentialRampToValueAtTime(0.001, c.currentTime + 4); o.connect(g); g.connect(this._mg); o.start(); o.stop(c.currentTime + 4); } catch (e) {} const t = setTimeout(bell, 3000 + Math.random() * 6000); this._nodes.push(() => clearTimeout(t)); }; bell(); },
    _aurora(c) { [520, 660, 440, 580].forEach((f, i) => { const o = c.createOscillator(), lfo = c.createOscillator(), g = c.createGain(), lg = c.createGain(); o.type = "sine"; o.frequency.value = f; lfo.frequency.value = 0.08 + i * 0.06; lg.gain.value = 0.018; g.gain.value = 0.022; lfo.connect(lg); lg.connect(g.gain); o.connect(g); g.connect(this._mg); o.start(); lfo.start(); this._nodes.push(o, lfo); }); },
    _dhoop(c) { this._mandir(c); }, _chandra(c) { this._cosmos(c); }, _raat(c) { this._forest(c); },
    _baul(c) { [220, 330, 440].forEach((f) => { const o = c.createOscillator(), g = c.createGain(), lfo = c.createOscillator(), lg = c.createGain(); o.type = "triangle"; o.frequency.value = f; lfo.frequency.value = 5; lg.gain.value = 1.5; lfo.connect(lg); lg.connect(o.frequency); g.gain.value = 0.04; o.connect(g); g.connect(this._mg); o.start(); lfo.start(); this._nodes.push(o, lfo); }); },
    _nodi(c) { this._ocean(c); }, _padma(c) { this._forest(c); }, _sandhya(c) { this._cosmos(c); },
    _kantha(c) { this._mandir(c); }, _grahan(c) { this._cosmos(c); }, _sakura(c) { this._forest(c); }, _desert(c) { this._wind(c); },
    _impulse(c) { if (this._ir) return this._ir; const len = Math.floor(c.sampleRate * 3.4), ir = c.createBuffer(2, len, c.sampleRate); for (let ch = 0; ch < 2; ch++) { const d = ir.getChannelData(ch); for (let i = 0; i < len; i++) d[i] = (Math.random() * 2 - 1) * Math.pow(1 - i / len, 2.6); } this._ir = ir; return ir; },
    _om(c) { [136.1, 272.2].forEach((f, i) => { const o = c.createOscillator(), g = c.createGain(), bp = this._bf(c, "bandpass", i ? 900 : 500, 4), lfo = c.createOscillator(), lg = c.createGain(); o.type = "sawtooth"; o.frequency.value = f; lfo.frequency.value = 0.06; lg.gain.value = 300; lfo.connect(lg); lg.connect(bp.frequency); g.gain.value = i ? 0.03 : 0.06; o.connect(bp); bp.connect(g); g.connect(this._mg); o.start(); lfo.start(); this._nodes.push(o, lfo); }); const hum = c.createOscillator(), hg = c.createGain(); hum.type = "sine"; hum.frequency.value = 68; hg.gain.value = 0.05; hum.connect(hg); hg.connect(this._mg); hum.start(); this._nodes.push(hum); },
    _choir(c) { const lp = this._bf(c, "lowpass", 1400, 0.6); lp.connect(this._mg); [196, 247, 294, 392].forEach((f, i) => { [0, 4].forEach((det) => { const o = c.createOscillator(), g = c.createGain(), lfo = c.createOscillator(), lg = c.createGain(); o.type = "sine"; o.frequency.value = f + det; lfo.frequency.value = 0.07 + i * 0.03; lg.gain.value = 0.012; g.gain.value = 0.016; lfo.connect(lg); lg.connect(g.gain); o.connect(g); g.connect(lp); o.start(); lfo.start(); this._nodes.push(o, lfo); }); }); },
    _bowls(c) { const drone = c.createOscillator(), dg = c.createGain(); drone.type = "sine"; drone.frequency.value = 110; dg.gain.value = 0.03; drone.connect(dg); dg.connect(this._mg); drone.start(); this._nodes.push(drone); const strike = () => { try { const f0 = 160 + Math.random() * 120; [1, 2.76, 5.4].forEach((m, i) => { const o = c.createOscillator(), g = c.createGain(); o.type = "sine"; o.frequency.value = f0 * m; g.gain.setValueAtTime(0.0001, c.currentTime); g.gain.exponentialRampToValueAtTime(0.12 / (i + 1), c.currentTime + 0.04); g.gain.exponentialRampToValueAtTime(0.0001, c.currentTime + 6); o.connect(g); g.connect(this._mg); o.start(); o.stop(c.currentTime + 6.2); }); } catch (e) {} const t = setTimeout(strike, 5000 + Math.random() * 7000); this._nodes.push(() => clearTimeout(t)); }; strike(); },
    _flute(c) { const o = c.createOscillator(), g = c.createGain(), vib = c.createOscillator(), vg = c.createGain(); o.type = "sine"; o.frequency.value = 440; vib.frequency.value = 5; vg.gain.value = 4; vib.connect(vg); vg.connect(o.frequency); g.gain.value = 0.05; o.connect(g); g.connect(this._mg); o.start(); vib.start(); this._nodes.push(o, vib); const scale = [392, 440, 494, 523, 587]; const phrase = () => { try { const f = scale[Math.floor(Math.random() * scale.length)]; o.frequency.setTargetAtTime(f, c.currentTime, 0.3); } catch (e) {} const t = setTimeout(phrase, 2500 + Math.random() * 3500); this._nodes.push(() => clearTimeout(t)); }; phrase(); const br = this._noise(c, "pink"), bf = this._bf(c, "bandpass", 1800, 1), bg = c.createGain(); bg.gain.value = 0.015; br.connect(bf); bf.connect(bg); bg.connect(this._mg); br.start(); this._nodes.push(br); },
    _ney(c) { const o = c.createOscillator(), g = c.createGain(), vib = c.createOscillator(), vg = c.createGain(); o.type = "sine"; o.frequency.value = 294; vib.frequency.value = 4.5; vg.gain.value = 5; vib.connect(vg); vg.connect(o.frequency); g.gain.value = 0.045; o.connect(g); g.connect(this._mg); o.start(); vib.start(); this._nodes.push(o, vib); const br = this._noise(c, "pink"), bf = this._bf(c, "bandpass", 1200, 0.8), bg = c.createGain(); bg.gain.value = 0.025; br.connect(bf); bf.connect(bg); bg.connect(this._mg); br.start(); this._nodes.push(br); },
    _tanpura(c) { const seq = [146.83, 220, 220, 146.83]; let i = 0; const pluck = () => { try { const f = seq[i % seq.length]; i++; const o = c.createOscillator(), g = c.createGain(), hp = this._bf(c, "highpass", 300, 0.7); o.type = "sawtooth"; o.frequency.value = f; g.gain.setValueAtTime(0.0001, c.currentTime); g.gain.linearRampToValueAtTime(0.08, c.currentTime + 0.02); g.gain.exponentialRampToValueAtTime(0.0001, c.currentTime + 2.4); o.connect(hp); hp.connect(g); g.connect(this._mg); o.start(); o.stop(c.currentTime + 2.5); } catch (e) {} const t = setTimeout(pluck, 1100); this._nodes.push(() => clearTimeout(t)); }; pluck(); const drone = c.createOscillator(), dg = c.createGain(); drone.type = "sine"; drone.frequency.value = 73.4; dg.gain.value = 0.04; drone.connect(dg); dg.connect(this._mg); drone.start(); this._nodes.push(drone); },
    _void(c) { [60, 67].forEach((f) => { const o = c.createOscillator(), g = c.createGain(); o.type = "sine"; o.frequency.value = f; g.gain.value = 0.06; o.connect(g); g.connect(this._mg); o.start(); this._nodes.push(o); }); },
  };

  function enable(on) { enabled = on; save(); if (on) { try { AMB._c(); } catch (e) {} AMB.play(preset); } else AMB.stop(); }
  function setPreset(p) { if (!p || p === preset) { if (enabled && !AMB._nodes.length) AMB.play(preset); return; } preset = p; if (enabled) AMB.play(p); }
  function setVolume(v) { vol = v; save(); if (AMB._mg) { try { AMB._mg.gain.setTargetAtTime(v, AMB._c().currentTime, 0.3); } catch (e) {} } }
  function resume() { try { if (enabled && AMB._ctx && AMB._ctx.state === "suspended") AMB._ctx.resume(); } catch (e) {} }
  load();
  return { enable, setPreset, setVolume, resume, isOn: () => enabled, vol: () => vol, init() {} };
})();
